FROM python:3.9-alpine

WORKDIR /app


# Install dependencies first (better caching)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# Then copy application code
COPY convert_image_to_pdf.pyconvert_image_to_pdf.py .


CMD ["python", "weather.py"]

